version: "3"
services:
  web:
    image: lullaboteducation/drupaldevwithdocker-php
    volumes:
      - ./docroot:/var/www/html:cached
    ports:
      - "80:80"
    env_file:
      - ./docker.env
  db:
    image:
      lullaboteducation/drupaldevwithdocker-mysql
    volumes:
      - ./db-backups:/var/mysql/backups:delegated
    env_file:
      - ./docker.env
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./docker.env
    ports:
      - "8001:80"
